### ISSUE TITLE
innerHTML needs special case for <template>

### ISSUE THREAD

**Issue by annevk** [w3c/DOM-Parsing#1]
@nox discovered in https://www.w3.org/Bugs/Public/show_bug.cgi?id=27314#c23 that fragment parsing in HTML does not work correctly. However, it would work correctly if `innerHTML` (and maybe the other APIs too) special case `<template>`. That seems to be the easiest way to address this problem and is how WebKit/Blink implement it reportedly.

Copying @bzbarsky and @hsivonen since they maybe be interested in this as well.

**Comment by nox** [comment]
insertAdjacentHTML(position, text) probably needs to be patched too.

**Comment by nox** [comment]
For further reference:

https://www.w3.org/Bugs/Public/show_bug.cgi?id=18794
https://github.com/w3c/webcomponents/commit/c3c46d87f9764a746523ec17853b0a5eb5ed46e0

**Comment by travisleithead** [comment]
I looked into innerHTML and confirmed the problem; outerHTML is protected because it uses the parent of the context object (though Chrome throws when the parent is a document fragment). insertAdjacentHTML is [oddly] interoperable in that it doesn't special-case `<template>`. I also don't think there can be a problem with createContextualFragment because it only returns the DocumentFragment and doesn't actually change the DOM.

@annevk please take a look at the PR to see if it can be improved.

**Comment by cscott** [comment]
I disagree with the PR: I think insertAdjacentHTML needs to be patched for consistency.  Nothing should add content to the direct children" of a <template> element: logically the children are the children of the document fragment.  The point of the insertAdjacentHTML method is to provide a safer mechanism to innerHTML manipulation; that objective is compromised if insertAdjacentHTML is inconsistent with innerHTML and does not provide access to the template content.

**Comment by nox** [comment]
Setting innerHTML on a template should change the template contents and not add children to the template itself.

**Comment by cscott** [comment]
@rniwa:
```
t = document.createElement('template');
t.innerHTML = '<p>ABC</p>';
t.insertAdjacentHTML('beforeend', 'def');
console.log(t.innerHTML);
```
Expected output on console is `<p>ABC</p>def`.
Output according to current spec is the empty string.

**Comment by cscott** [comment]
(The domino commit referenced above also contains a test case illustrating the spec bug.)

**Comment by travisleithead** [comment]
@cscott 
>  Nothing should add content to the direct children" of a element: logically the children are the children of the document fragment.

I think you must be specifically referring to APIs that invoke the HTML parser, because I would strongly disagree with you, if you wanted to change appendChild behavior for `<template>`.

Also, the PR as written is documenting interoperable behavior in at least public Firefox/Edge/Chrome. If we want to change this, we have to have changes across at least three browsers... so while I agree that this inconsistency is weird, I'm very hesitant to write aspirational prose unless all browsers are on board to change their behavior.

**Comment by travisleithead** [comment]
... and checked with Safari 9 Tech Preview: results consistent with other browsers tested.

**Comment by rniwa** [comment]
Yeah, I remember the discussion back in days.  As far as I recall, the consensus was to special case `innerHTML` for convenience and all other DOM APIs won't have a special case for `template` since you can access the content's `DocumentFragment` via `template.content`.

**Comment by ajklein** [comment]
What @travisleithead said sounds right to me: only innerHTML is special-cased in Chromium (and other browsers) at the moment, and it's worth making sure that's well-documented by the spec.

As to the question of whether insertAdjacentHTML also ought to be special-cased, that seems like a separate question which should be considered separately.

**Comment by rniwa** [comment]
I think merging this PR into DOM parsing as an improvement as is since that would at least document the status quo that `innerHTML` is special.  If people are interested in also changing the behavior of `insertAdjacentHTML` for `template` element, then we should probably track that in a separate issue.

**Comment by cscott** [comment]
I'm convinced by @rniwa, @ajklein, and @travisleithead that PR #12 is internally consistent: innerHTML/outerHTML are special, but direct Node manipulation APIs (addChild, insertAdjacentHTML, etc) should be untouched.  I'll make one suggestion to the spec text (as a comment on PR#12) which will hopefully clarify the underlying consistency to readers.

**Comment by travisleithead** [comment]
Thanks all. Applied @cscott's recommended prose for the note.

**Comment by cscott** [comment]
Works for me.  Thanks!
