### ISSUE TITLE
DOMParser's parseFromString should have CEReactions

### ISSUE THREAD

**Issue by rniwa** [w3c/DOM-Parsing#22]
[`DOMParser`](https://w3c.github.io/DOM-Parsing/#the-domparser-interface)'s [`parseFromString`](https://w3c.github.io/DOM-Parsing/#dom-domparser-parsefromstring) should have `CEReactions` IDL attribute since it can add attributes to a newly constructed custom elements.

**Comment by rniwa** [comment]
@travisleithead @domenic @annevk

**Comment by domenic** [comment]
I wonder how we missed that, especially given that we added it to createContextualFragment.

I'll PR this tomorrow. Thanks for catching.

**Comment by domenic** [comment]
Ah, no, I remember the reason why we didn't have CEReactions here. The reason might be wrong though; I'd appreciate your analysis. But I think that since parseFromString creates a new document without a browsing context, no elements created in that document can be custom.

I tried to look at the test you added in https://github.com/w3c/web-platform-tests/pull/3967/files, but I think the test might be wrong? The element should not get constructed using the constructor, and no callbacks should run. A negative test might be useful...

**Comment by rniwa** [comment]
Yeah, you're right. This isn't needed.

**Comment by rniwa** [comment]
Yeah, this appears to be unneeded. In fact, we have WPT tests to ensure `parseFromString` creates a new document.

**Comment by domenic** [comment]
At TPAC reviewed this and agreed it was not necessary after all.
